name: Run Cyber Digital Twin Pipeline

on:
  push:
    branches: [ main ]         # Pour déclencher à chaque mise à jour de code
  workflow_dispatch:           # Pour lancer manuellement si besoin
  schedule:
    - cron: '0 3 * * *'        # Exécution automatique tous les jours à 4h heure tunisienne (3h UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Etape 1: Installer Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Etape 2: Mettre à jour pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Etape 3: Clear pip cache
      - name: Clear pip cache
        run: pip cache purge

      # Etape 4: Installer PyTorch et ses dépendances compatibles avec CPU
      - name: Install PyTorch (CPU)
        run: |
          pip install torch==2.0.1+cpu torchvision==0.15.1+cpu torchaudio==2.0.2+cpu --index-url https://download.pytorch.org/whl/cpu
          pip install torch-scatter==2.1.0 -f https://data.pyg.org/whl/torch-2.0.1+cpu.html
          pip install torch-sparse==2.1.0 -f https://data.pyg.org/whl/torch-2.0.1+cpu.html
          pip install torch-cluster==1.6.0 -f https://data.pyg.org/whl/torch-2.0.1+cpu.html
          pip install torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-2.0.1+cpu.html
          pip install torch-geometric

      # Etape 5: Installer les autres dépendances nécessaires (si non incluses dans requirements.txt)
      - name: Install other dependencies
        run: pip install -r requirements.txt

      # Etape 6: Vérifier les versions des paquets installés
      - name: Debug installed packages
        run: pip list

      # Etape 7: Exécuter le script rotatE_Rgcn.py
      - name: Run rotatE_Rgcn
        run: python rotatE_Rgcn.py

    
